### ISSUE TITLE
Call to action on user/recipient profile pages

### ISSUE THREAD

**Issue by nehzata** [thnxdev/issues#17]
When a GH user adds their TD profile to their FUNDING.yml file in a repo, a potential donor lands on a page such as [this](https://thanks.dev/u/gh/pboling). We should have a CTA here to guide them through signing up and setting up a donation so this profile can get funded. As is, the flow is broken at the moment. What should I do next when I land on this page?

@vladh fyi

**Comment by vladh** [comment]
Do we just want to direct new donors to the regular sign-up flow? Or do we want to create a flow where pboling is somehow prioritised in the new donors's payments? 🤔

**Comment by nehzata** [comment]
Maybe let's just start with directing towards regular sign-up flow for now? Simpler and easier bang for buck right?
