### ISSUE TITLE
polish: sponsor/maintainer dropdown => toggle

### ISSUE THREAD

**Issue by kylemann** [thnxdev/issues#5]
## Problem to solve

thanks.dev is a two sided market place, for sponsors and maintainers. Upon landing on the page it defaults to sponsors – though the experience is different for maintainers. The current toggle on marketing page and in product is hidden in time.

<img width="871" alt="Screenshot 2024-10-28 at 9 28 38 AM" src="https://github.com/user-attachments/assets/4ce616f5-855b-42d8-93be-4ee18845a026">

## Solution suggestion

Display element options in space and not time, making them visible at all times to differing audiences. 

<img width="871" alt="toggle_thanks_dev" src="https://github.com/user-attachments/assets/7ff45b8f-bd97-43b0-9f0b-7d76f39bbd6d">

**Comment by vladh** [comment]
Sounds good to me. More generally, I think we should also clarify when maintainers can act as sponsors, eg through redonations. There was some confusion about this in Discord recently.

![2024-10-28-15-52-07](https://github.com/user-attachments/assets/3847a92c-79d5-42fd-83ee-cc83b3466e62)

**Comment by nehzata** [comment]
Awesome suggestion @kylemann. Deployed!
