### ISSUE TITLE
polish: include human avatars and logos

### ISSUE THREAD

**Issue by kylemann** [thnxdev/issues#6]
## Problem

Less of a polish-nitpick and more about a small iteration toward larger suggestion of helping the sponsors see results by putting a face to the name. The dependency tree concept direction makes sense, in terms on a unique way to  distribute sponsorship according to repo usage. The issue is that ultimately it's more compelling to see the hands the money ends up in vs the project. Example from nonprofits is they will often show the individual and impact of a donation _to an individual_, since this better outlines results vs donating to a black hole. 

<img width="989" alt="Screenshot 2024-10-28 at 9 38 44 AM" src="https://github.com/user-attachments/assets/820e139e-ffd2-4f29-aef6-fff4f4b40677">

<img width="1010" alt="Screenshot 2024-10-28 at 9 45 43 AM" src="https://github.com/user-attachments/assets/e44a79eb-1b28-4dec-b84c-fac4008572cf">

I'll create a longer ticket about this issue...

## Solution

All that to say, the small iteration here is to inherit the org or username logo from GH and/or GitLab

![avatar_gh](https://github.com/user-attachments/assets/230bc856-35a7-4544-a904-7b44ed193fbc)

**Comment by vladh** [comment]
We just started saving avatars, for GitHub at least, so it would be easy to get an implementation going.

**Comment by nehzata** [comment]
Deployed! (gh only for the moment. covers 98% of the cases)
